# Generated by Django 4.2.5 on 2024-01-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='profile_pics/2.jpg', upload_to='profile_pics'),
        ),
    ]
