# Generated by Django 4.2.5 on 2024-01-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_topic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='2.jpg', upload_to='profile_pics'),
        ),
    ]
